# -*- coding: utf-8 -*-
"""Funcoes_Fila.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4e9O4MtnvZVg9s1AMufb8IP6FqWXxQt
"""

from collections import deque

# Criando a fila
fila = deque()

def enfileirar(elemento):
    """Insere elemento no final da fila"""
    fila.append(elemento)
    print(f"Elemento '{elemento}' enfileirado com sucesso!")

def desenfileirar():
    """Remove elemento do início da fila"""
    if fila:
        elemento = fila.popleft()
        print(f"Elemento '{elemento}' removido da fila.")
    else:
        print("A fila está vazia, não há elementos para remover.")

def consultar():
    """Exibe o elemento do início da fila sem removê-lo"""
    if fila:
        print(f"O primeiro elemento da fila é: {fila[0]}")
    else:
        print("A fila está vazia.")

def contar():
    """Exibe a quantidade de elementos na fila"""
    print(f"A fila possui {len(fila)} elemento(s).")

def menu():
    while True:
        print("\n--- MENU FILA ---")
        print("1 - Enfileirar")
        print("2 - Desenfileirar")
        print("3 - Consultar primeiro elemento")
        print("4 - Contar elementos")
        print("5 - Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            elemento = input("Digite o elemento a ser enfileirado: ")
            enfileirar(elemento)
        elif opcao == "2":
            desenfileirar()
        elif opcao == "3":
            consultar()
        elif opcao == "4":
            contar()
        elif opcao == "5":
            print("Encerrando o programa...")
            break
        else:
            print("Opção inválida. Tente novamente.")

if __name__ == "__main__":
    menu()